### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mojodna** [futpib/eslint-template-visitor#2]
At present, the `license` field in `package.json` says that this falls under either the GPL version 3.0 **or** MIT licenses.

https://github.com/futpib/eslint-template-visitor/blob/c0cfa58d8ed9439b995b505d5f9c8150ca1cd38b/package.json#L5

Is that intentional? If so, I'm not sure how to interpret it. I would practically always choose to consume it under an MIT license, as that gives me more flexibility.

**Comment by futpib** [comment]
Yes, this is a valid [SPDX expression](https://spdx.org/spdx-specification-21-web-version) idicating a choice between [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html) and [MIT](https://spdx.org/licenses/MIT.html). You can use it under one or the other. It's not a unique combination for `eslint-template-visitor` as can be seen in [github search](https://github.com/search?o=desc&q=filename%3Apackage.json+%22OR%22+MIT+GPL&s=indexed&type=Code).
