### ISSUE TITLE
Support ESLint 7x

### ISSUE THREAD

**Issue by himynameisdave** [futpib/eslint-template-visitor#8]
Support ESLint 7.x [as a `peerDependency`](https://github.com/futpib/eslint-template-visitor/blob/master/package.json#L7). Might be other changes in this package to support ESLint 7, but I don't think so (this assumption is based on me using this package as a transitive dependency of [`eslint-plugin-unicorn@20.0.0`](https://github.com/sindresorhus/eslint-plugin-unicorn).

I'm not sure if we still care about listing / supporting `eslint@ < 7`, but we could include that it like

```json
"peerDependencies": {
  "eslint": "^6 || ^7"
},
```

Happy to open a PR once I know what versions `eslint-template-visitor` should officially support.

**Comment by futpib** [comment]
Published `eslint-template-visitor@2.0.0` with a peer dependency on `"eslint": ">=7.0.0"`, since that's what `eslint-plugin-unicorn` lists (and that is the only dependent I know of). Hope that works for you.

**Comment by himynameisdave** [comment]
Thanks for addressing this so quickly!
